### ISSUE TITLE
Relevamiento

### ISSUE THREAD

**Issue by FranciscoRodriguezC** [InstitutoPascal/adminwebpro#13]
Nos reunimos con la profesora Vargas (Contadora) en el cuál  nos mostró un sistema  contable (por medio de un video)  con  todos sus módulos,  necesarios para un correcto manejo del sistema. 
Nos aclaró que los subdiarios son lo mas importante para el contador por la que es necesario incluirlo en nuestro sistema.

**Comment by NicolasCugliari** [comment]
La entrevista fue muy buena y orientadora, ya que no teníamos muy bien en claro por donde encarar el proyecto pero pudimos aclarar varias dudas.
