### ISSUE TITLE
Programar vista de detalle de ventas

### ISSUE THREAD

**Issue by IvanZ2016** [InstitutoPascal/adminwebpro#218]
Ya seleccionado el cliente que aparesca el nombre, fecha y numero de comprobante.
Buscar el producto desde la Base de Datos.
Segun el producto su Precio de venta.
Que el boton AGREGAR ITEM, valla agregando productos a la tabla.
Que los botones ELIMINAR y MODIFICAR cumpla su funcion por cada campo.
Que nos de los correspondientes resultados de los totales.

**Comment by Jorgedbd** [comment]
Luego de terminar la vista de FACTURAR se lograron los objetivos para poder pasar a la siguiente vista y terminar lo propuesto para que este funcione de la mejor manera
